### ISSUE TITLE
What is the meaning of 1000 in the final return of the loss function?

### ISSUE THREAD

**Issue by wansiwei0521** [tonylitianyu/Preference-Planning-Deep-IRL#1]
https://github.com/tonylitianyu/Preference-Planning-Deep-IRL/blob/5b496d75502ef530bee49b41f789f40eb2c14015/loss_fn.py#L6-L14

**Comment by tonylitianyu** [comment]
I was testing scaling up the loss to see whether it will speed up the converging process or not. It did not change too much and I forgot to delete it. Sorry about the confusion.

**Comment by wansiwei0521** [comment]
Thank you very much for your reply, this project is very helpful to me.
